management:
  security:
    enabled: false

server:
  port: ${port:8080}

spring:
  cloud:
    config:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
